// ==========================================================================
// This is auto-generated by gf cli tool. Fill this file as you wish.
// ==========================================================================

package model

import (
	"evan-gf/app/model/internal"
)

// User is the golang structure for table user.
type User internal.User

const (
	Normal  = 1
	Disable = -1
)

// Fill with you ideas below.
type UserLoginInfo struct {
	Id       uint   `json:"id"`
	Name     string `json:"name"`
	NickName string `json:"nick_name"`
}

type ServiceRegisterReq struct {
	Name     string `json:"name"`
	Password string `json:"password"`
	NickName string `json:"nick_name"`
}
