// ==========================================================================
// This is auto-generated by gf cli tool. DO NOT EDIT THIS FILE MANUALLY.
// ==========================================================================

package internal

import (
	"github.com/gogf/gf/os/gtime"
)

// User is the golang structure for table user.
type User struct {
	Id       uint        `orm:"id,primary" json:"id"`       // 用户ID
	Name     string      `orm:"name"       json:"name"`     // 用户账号
	NickName string      `orm:"nick_name"  json:"nickName"` // 用户昵称
	Password string      `orm:"password"   json:"password"` // 用户密码
	Status   int         `orm:"status"     json:"status"`   // 用户状态：1/正常,-1/禁用
	CreateAt *gtime.Time `orm:"create_at"  json:"createAt"` // 创建时间
	UpdateAt *gtime.Time `orm:"update_at"  json:"updateAt"` // 更新时间
}
