[server]
    address = ":6061"

[swagger]
    debug = true

[database]
    [[database.default]]
        type = "mysql"
        link = "root:root@tcp(127.0.0.1:3306)/gf"
    [[database.shop]]
        type = "mysql"
        link = "mysql:root:root@tcp(127.0.0.1:3306)/gf"
        debug = true



[gfcli]
    [[gfcli.gen.dao]]
        link   = "mysql:root:root@tcp(127.0.0.1:3306)/gf"
        prefix = ""
        tables = "user"
#         overwriteDao = true