// ============================================================================
// This is auto-generated by gf cli tool only once. Fill this file as you wish.
// ============================================================================

package dao

import (
	"evan-gf/app/dao/internal"
	"evan-gf/app/model"
)

// userDao is the manager for logic model data accessing
// and custom defined data operations functions management. You can define
// methods on it to extend its functionality as you wish.
type userDao struct {
	internal.UserDao
}

var (
	// User is globally public accessible object for table user operations.
	User = userDao{
		internal.User,
	}
)

// Fill with you ideas below.
func (u *userDao)ExistByNickName(nickName string) bool {
	var user *model.User
	u.Where("nickname",nickName).Scan(&user)
	if user != nil {
		return true
	}
	return false
}